name: Build Crates

on:
  pull_request:
    paths:
      - 'crate/**'
      - 'Cargo.toml'
      - 'rustfmt.toml'
      - '.github/workflows/build-crates.yml'

  push:
    branches: [ 'main' ]
    tags-ignore: [ '*' ]
    paths:
      - 'crate/**'
      - 'Cargo.toml'
      - 'rustfmt.toml'
      - '.github/workflows/build-crates.yml'

  workflow_dispatch:

env:
  RUST_BACKTRACE: full
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  CARGO_INCREMENTAL: 0

jobs:
  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #        os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ macos-latest ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.11.0

      - name: Configure cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Run cargo test
        run: cargo test --all-features